### ISSUE TITLE
Conflict occurred

### ISSUE THREAD

**Issue by iamsoNewBee** [DylanLogan2581/AncientWarfare3#1]
When the lastest vision was added with AgriCraft in 1.7.10,the game will crash.

[crash-2022-06-27_18.48.20-client.txt](https://github.com/DylanLogan2581/AncientWarfare3/files/8991198/crash-2022-06-27_18.48.20-client.txt)

By the way ,this new vision is really surprised me.I have never thought that it will update in 1.7.10!

**Comment by zerozaki666** [comment]
> When the lasted vision was added with AgriCraft in 1.7.10,the game will crash.
> 
> [crash-2022-06-27_18.48.20-client.txt](https://github.com/DylanLogan2581/AncientWarfare3/files/8991198/crash-2022-06-27_18.48.20-client.txt)
> 
> By the way ,this new vision is really surprised me.I have never thought that it will update in 1.7.10!

Same crash here same situation.

**Comment by iamsoNewBee** [comment]
> > When the lasted vision was added with AgriCraft in 1.7.10,the game will crash.
> > [crash-2022-06-27_18.48.20-client.txt](https://github.com/DylanLogan2581/AncientWarfare3/files/8991198/crash-2022-06-27_18.48.20-client.txt)
> > By the way ,this new vision is really surprised me.I have never thought that it will update in 1.7.10!
> 
> Same crash here same situation.

But I dont think he will fix it...(Maybe he will give us another surprise?)

**Comment by DylanLogan2581** [comment]
This is a result of the API classpath changing. I am going to fix this now. Sorry I didn't see this!

**Comment by DylanLogan2581** [comment]
Version 3.0.2 fixes this.

**Comment by iamsoNewBee** [comment]
LOVE YOU

**Comment by DDRAIGOCH117** [comment]
Where can i get version 3.0.2?

**Comment by iamsoNewBee** [comment]
> Where can i get version 3.0.2?
SAME QUSETION

**Comment by DylanLogan2581** [comment]
Sorry. I got sidetracked with school. I  havent had time to test this yet. If someone tries this please let me know if its working with agricraft? The jar is in the zip. When I get time I will push the changes and upload it to the normal sites.

[ancientwarfare302.zip](https://github.com/DylanLogan2581/AncientWarfare3/files/10363373/ancientwarfare302.zip)

**Comment by iamsoNewBee** [comment]
it works thank you
