### ISSUE TITLE
Ticking entity (Probably a bad interaction between mods) 

### ISSUE THREAD

**Issue by DDRAIGOCH117** [DylanLogan2581/AncientWarfare3#3]
[crash-2023-01-07_16.31.20-server.txt](https://github.com/DylanLogan2581/AncientWarfare3/files/10367345/crash-2023-01-07_16.31.20-server.txt)
Using Beta version 3.0.2

**Comment by iamsoNewBee** [comment]
what the tiling entity means?

**Comment by DylanLogan2581** [comment]
If you have anymore info I would be happy to help.

1) What exactly happened when you crashed? Or was it seeming random?
2) Can you recreate the crash without all the other mods?
3) What is the minimum amount of mods you can recreate the crash with? Which mods?
